name: CI

on: [push]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn typecheck

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14, 16]
    name: Test - Node.js ${{ matrix.node_version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn test --ci --coverage
    - uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: node${{ matrix.node }}
        parallel: true

  test-finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn build
