name: CI

on: [push]

env:
  DEFAULT_NODE_VERSION: 16

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.DEFAULT_NODE_VERSION }}
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
        graphqljs: ['16.x']
        include:
        - { node: '16', graphqljs: '15.0.0' }
        - { node: '16', graphqljs: '15.x' }
        - { node: '16', graphqljs: '16.0.0' }
        - { node: '16', graphqljs: '16.x' }
    name: Test - Node.js ${{ matrix.node }}, graphql ${{ matrix.graphqljs }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn test --ci --coverage
      env:
        GRAPHQLJS_VERSION: ${{ matrix.graphqljs }}
    - uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: node${{ matrix.node }}-graphql@${{ matrix.graphqljs }}
        parallel: true

  test-finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.DEFAULT_NODE_VERSION }}
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn build
