name: CI

on: [push]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn test

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14, 16]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn typecheck

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn build
